# Results for NL-SGD (Small and Medium Datasets)
## Compared with NN-ISDA (Zigic Lj) & MN-SVM (Strack R)
### by: Gabriella Melki

### Clear Workspace and Import Libraries
```{r echo=TRUE, cache=TRUE}
rm(list=ls())
library(ggplot2)
```
### set width and height of plots
```{r echo=TRUE, cache=TRUE}
w <- 800
h <- 480
```

### SGD vs. NNISDA & MNSVM
#### Small Data
##### Accuracy
```{r echo=TRUE, cache=TRUE}
smldata_accuracy_compare <- read.csv("AccuracyComparisonSmallData.csv", header = TRUE)
smldata_accuracy_compare$Algorithm <- factor(smldata_accuracy_compare$Algorithm, levels = c("NL-SGD", "NN-ISDA", "MN-SVM"))
head(smldata_accuracy_compare)

png("AccuracyComparisonSmallData.png", width = w, height = h, units = "px", bg="transparent")

g_plot <- ggplot(smldata_accuracy_compare, aes(x=Dataset,y=Accuracy)) +
  geom_bar(aes(fill=Algorithm),position = "dodge", stat = "identity") +
  scale_fill_manual(values=c("#E69F00", "Blue", "Red")) +
  facet_grid(scales="free", space="free", .~Dataset) +
  theme(axis.ticks = element_blank(), axis.text.x = element_blank(), axis.title.x = element_blank()) +
  labs(x = element_blank(), y = "Accuracy %") + 
  ggtitle(expression(atop("Accuracy Comparison", atop("for Small Data Sets", ""))))
print(g_plot)
dev.off()
print(g_plot)
```
##### CPU Time
```{r echo=TRUE, cache=TRUE}
smldata_cpu_compare <- read.csv("CPUTimeComparison_SmallData.csv", header = TRUE)
smldata_cpu_compare$Algorithm <- factor(smldata_cpu_compare$Algorithm, levels = c("NL-SGD", "NN-ISDA", "MN-SVM"))
head(smldata_cpu_compare)

proeuk <- smldata_cpu_compare[smldata_cpu_compare[,"Dataset"] == "Prokaryotic" | smldata_cpu_compare[,"Dataset"] == "Eukaryotic",]
smldata_cpu_compare <- smldata_cpu_compare[smldata_cpu_compare[,"Dataset"] != "Prokaryotic" & smldata_cpu_compare[,"Dataset"] != "Eukaryotic",]

png("CPUTimeComparison_SmallData.png", width = w, height = h, units = "px", bg="transparent")

g_plot <- ggplot(smldata_cpu_compare, aes(x=factor(Dataset), y=CPU)) +
  geom_bar(aes(fill=Algorithm),position = "dodge", stat = "identity") +
  scale_fill_manual(values=c("#E69F00", "Blue", "Red")) +
  facet_grid(scales="free", space="free", .~Dataset) +
  theme(axis.ticks = element_blank(), axis.text.x = element_blank(), axis.title.x = element_blank()) +
  labs(y = "CPU Time (s)") + 
  ggtitle(expression(atop("CPU Time Comparison", atop("for Small Data Sets", ""))))
print(g_plot)
dev.off()
print(g_plot)

png("CPUTimeComparison_SmallData_ProkEuk.png", width = w, height = h, units = "px", bg="transparent")

g_plot <- ggplot(proeuk, aes(x=factor(Dataset), y=CPU)) +
  geom_bar(aes(fill=Algorithm),position = "dodge", stat = "identity") +
  scale_fill_manual(values=c("#E69F00", "Blue", "Red")) +
  facet_grid(scales="free", space="free", .~Dataset) +
  theme(axis.ticks = element_blank(), axis.text.x = element_blank(), axis.title.x = element_blank()) +
  labs(y = "CPU Time (s)") + 
  ggtitle(expression(atop("CPU Time Comparison", atop("for Prokaryotic & Eukaryotic Data Sets", ""))))
print(g_plot)
dev.off()
print(g_plot)

rm(proeuk)
```
#### Medium Data
##### Accuracy
```{r echo=TRUE, cache=TRUE}
meddata_accuracy_compare <- read.csv("AccuracyComparison_MediumData.csv", header = TRUE)
meddata_accuracy_compare$Algorithm <- factor(meddata_accuracy_compare$Algorithm, levels = c("NL-SGD", "NN-ISDA", "MN-SVM"))
head(meddata_accuracy_compare)

png("AccuracyComparison_MediumData.png", width = w, height = h, units = "px", bg="transparent")

g_plot <- ggplot(meddata_accuracy_compare, aes(x=factor(Dataset), y=ACC)) +
  geom_bar(aes(fill=Algorithm),position = "dodge", stat = "identity") +
  scale_fill_manual(values=c("#E69F00", "Blue", "Red")) +
  facet_grid(scales="free", space="free", .~Dataset) +
  theme(axis.ticks = element_blank(), axis.text.x = element_blank(), axis.title.x = element_blank()) +
  labs(y = "Accuracy %") + 
  ggtitle(expression(atop("Accuracy Comparison", atop("for Medium Data Sets", ""))))
print(g_plot)
dev.off()
print(g_plot)
```
##### CPU Time
```{r echo=TRUE, cache=TRUE}
meddata_cpu_compare <- read.csv("CPUTimeComparison_MediumData.csv", header = TRUE)
meddata_cpu_compare$Algorithm <- factor(meddata_cpu_compare$Algorithm, levels = c("NL-SGD", "NN-ISDA", "MN-SVM"))
head(meddata_cpu_compare)

png("CPUTimeComparison_MediumData.png", width = w, height = h, units = "px", bg="transparent")

g_plot <- ggplot(meddata_cpu_compare, aes(x=factor(Dataset), y=CPU)) +
  geom_bar(aes(fill=Algorithm),position = "dodge", stat = "identity") +
  scale_fill_manual(values=c("#E69F00", "Blue", "Red")) +
  facet_grid(scales="free", space="free", .~Dataset) +
  theme(axis.ticks = element_blank(), axis.text.x = element_blank(), axis.title.x = element_blank()) +
  labs(y = "CPU Time (s)") + 
  ggtitle(expression(atop("CPU Time Comparison", atop("for Medium Data Sets", ""))))
print(g_plot)
dev.off()
print(g_plot)
```
### SGD Configurations
#### Small Data
##### Accuracy
```{r echo=TRUE, cache=TRUE}
SGD_SmallData <- read.csv("SGD_SmallData.csv", header = TRUE)
head(SGD_SmallData)

png("SGDAccuracy_SmallData.png", width = w, height = h, units = "px", bg="transparent")

g_plot <- ggplot(SGD_SmallData, aes(x=factor(KT), y=ACCURACY)) +
  geom_bar(aes(group=interaction(KT,NEPOCH),fill=factor(NEPOCH)),position = "dodge", stat = "identity") +
  guides(fill=guide_legend(title="Number of Epochs")) +
  facet_grid(scales="free", space="free", .~DATASET) +
  labs(x = "Percent of Alpha Changes", y = "Accuracy %") + 
  ggtitle(expression(atop("NL-SGD Accuracy", atop("for Small Data Sets", ""))))
print(g_plot)
dev.off()
print(g_plot)
```
##### CPU Time
```{r echo=TRUE, cache=TRUE}
proeuk <- SGD_SmallData[SGD_SmallData[,"DATASET"] == "Prokaryotic" | SGD_SmallData[,"DATASET"] == "Eukaryotic",]
SGD_SmallData <- SGD_SmallData[SGD_SmallData[,"DATASET"] != "Prokaryotic" & SGD_SmallData[,"DATASET"] != "Eukaryotic",]

png("SGDCPUTime_SmallData.png", width = w, height = h, units = "px", bg="transparent")

g_plot <- ggplot(SGD_SmallData, aes(x=factor(KT), y=CPU)) +
  geom_bar(aes(group=interaction(KT,NEPOCH),fill=factor(NEPOCH)),position = "dodge", stat = "identity") +
  guides(fill=guide_legend(title="Number of Epochs")) +
  facet_grid(scales="free", space="free", .~DATASET) +
  labs(x = "Percent of Alpha Changes", y = "CPU Time (s)") + 
  ggtitle(expression(atop("NL-SGD CPU Time", atop("for Small Data Sets", ""))))
print(g_plot)
dev.off()
print(g_plot)

png("SGDCPUTime_SmallData_ProEuk.png", width = w, height = h, units = "px", bg="transparent")

g_plot <- ggplot(proeuk, aes(x=factor(KT), y=CPU)) +
  geom_bar(aes(group=interaction(KT,NEPOCH),fill=factor(NEPOCH)),position = "dodge", stat = "identity") +
  guides(fill=guide_legend(title="Number of Epochs")) +
  facet_grid(scales="free", space="free", .~DATASET) +
  labs(x = "Percent of Alpha Changes", y = "CPU Time (s)") + 
  ggtitle(expression(atop("NL-SGD CPU Time", atop("for Small Data Sets", ""))))
print(g_plot)
dev.off()
print(g_plot)

rm(proeuk)
```
#### Medium Data
##### Accuracy
```{r echo=TRUE, cache=TRUE}
SGD_MediumData <- read.csv("SGD_MediumData.csv", header = TRUE)
head(SGD_MediumData)

png("SGDAccuracy_MediumData.png", width = w, height = h, units = "px", bg="transparent")

g_plot <- ggplot(SGD_MediumData, aes(x=factor(KT), y=ACCURACY)) +
  geom_bar(aes(group=interaction(KT,NEPOCH),fill=factor(NEPOCH)),position = "dodge", stat = "identity") +
  guides(fill=guide_legend(title="Number of Epochs")) +
  facet_grid(scales="free", space="free", .~DATASET) +
  labs(x = "Percent of Alpha Changes", y = "Accuracy %") + 
  ggtitle(expression(atop("NL-SGD Accuracy", atop("for Medium Data Sets", ""))))
print(g_plot)
dev.off()
print(g_plot)
```
##### CPU Time
```{r echo=TRUE, cache=TRUE}
png("SGDCPUTime_MediumData.png", width = w, height = h, units = "px", bg="transparent")

g_plot <- ggplot(SGD_MediumData, aes(x=factor(KT), y=CPU)) +
  geom_bar(aes(group=interaction(KT,NEPOCH),fill=factor(NEPOCH)),position = "dodge", stat = "identity") +
  guides(fill=guide_legend(title="Number of Epochs")) +
  facet_grid(scales="free", space="free", .~DATASET) +
  labs(x = "Percent of Alpha Changes", y = "CPU Time (s)") + 
  ggtitle(expression(atop("NL-SGD CPU Time", atop("for Medium Data Sets", ""))))
print(g_plot)
dev.off()
print(g_plot)
```